<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headScript(); ?>
	<?php echo $this->headStyle(); ?>
</head>
<body>
<!-- content -->
<div class="secontainer">
	<?php echo $this->layout()->content; ?>
</div>
<!-- /content -->

<script type="text/javascript">//<!--
// A workaround for browsers which don't support Data URI
var data = new Image();
data.onload = data.onerror = function () {
    if (this.width != 1 || this.height != 1) {
        $('img[data-fallbacksrc]').each(function () {
            $(this).attr('src', $(this).attr('data-fallbacksrc'));
        });
    }
};
data.src = "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==";
//-->
</script>

</body>
</html>
