<?php if ($this->pageCount) { ?>
<div class="pagination pagination-right">
	<ul class="pagination">
		<!-- Previous page link -->
		<?php if (isset($this->previous)) { ?>
		<li><a href="?q=<?php echo $this->url(array('page' => $this->previous)); ?>">&laquo;</a></li>
		<?php } else { ?>
		<li class="disabled"><a href="#">&laquo;</a></li>
		<?php } ?>
		
		<!-- Numbered page links -->
		<?php foreach ($this->pagesInRange as $page) { ?>
		  <?php if ($page != $this->current) { ?>
			<li><a href="?q=<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>
		  <?php } else { ?>
			<li class="active"><a href="#"><?php echo $page; ?></a></li>
		  <?php } //endif ?>
		<?php } // foreach ?>		
				
		<!-- Next page link -->
		<?php if (isset($this->next)) { ?>
		<li><a href="?q=<?php echo $this->url(array('page' => $this->next)); ?>">&raquo;</a></li>
		<?php } else { ?>
		<li class="disabled"><a href="#">&raquo;</a></li>
		<?php } ?>
	</ul>
</div>
<?php } ?>